version: '3'

services:
  # Fix n8n port conflict with Supabase
  n8n:
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=https://n8n.${DOMAIN_NAME:-kwintes.cloud}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-https}
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_METRICS_ENABLED=true

  # Fix WebUI port mapping
  open-webui:
    ports:
      - "3000:8080"
    networks:
      - monitoring

  # Ensure all services use the monitoring network
  searxng:
    networks:
      - monitoring
    
  ollama-cpu:
    networks:
      - monitoring

  ollama-gpu:
    networks:
      - monitoring

  ollama-gpu-amd:
    networks:
      - monitoring

  flowise:
    networks:
      - monitoring

  qdrant:
    networks:
      - monitoring

  prometheus:
    networks:
      - monitoring

  grafana:
    networks:
      - monitoring

  redis:
    networks:
      - monitoring 